<header class="same-step-header">
	<h2><?php echo $this->__( 'Choose a Shipping Method' ); ?></h2>
	<h3 class="mob-head show-iphone"><?php echo $this->__( 'Choose a Shipping Method' ); ?></h3>
	<small id="shipping-buttons-container">
		<small id="shipping-please-wait" class="please-wait" style="display: none;">
			<img src="<?php echo $this->getSkinUrl( 'images/anattadesign/awesomecheckout/opc-ajax-loader.gif' ) ?>" alt="Loading next step..." title="Loading next step..." class="v-middle">
		</small>
	</small>
</header>
<form id="co-shipping-method-form" action="<?php echo $this->getUrl( 'checkout/onepage/saveShippingMethod' ) ?>" method="post">
	<div id="checkout-shipping-method-load-wrapper">
		<?php if ( $specialAnnouncement = Mage::getStoreConfig( 'awesomecheckout/shipping_method/special_announcement' ) ): ?>
			<div class="special-announcement message">
				<div>
					<h2><?php echo $this->__( 'Special Announcement' ) ?></h2>
					<p><?php echo $specialAnnouncement ?></p>
				</div>
			</div>
		<?php endif; ?>
		<div id="checkout-shipping-method-schedule-wrapper" class="clearfix">
			<div id="checkout-shipping-method-load">
				<?php echo $this->getChildHtml( 'available' ) ?>
			</div>
		</div>
		<div id="checkout-shipping-method-totals-wrapper">
			<?php echo $this->__('Updated Total: ') ?><span><?php echo $this->helper( 'checkout' )->formatPrice( Mage::getSingleton( 'checkout/session' )->getQuote()->getGrandTotal() ) ?></span>
		</div>
	</div>
	<script type="text/javascript">
		//<![CDATA[
		var shippingMethod = new ShippingMethod({ form: '#co-shipping-method-form' });
		//]]>
	</script>
	<footer id="shipping-method-buttons-container">
		<input type="submit" class="button" onclick="shippingMethod.save();return false;" value="<?php echo $this->__( 'Proceed to Payment &rarr;' ) ?>"/>
		<span id="shipping-method-please-wait" class="please-wait" style="display:none;">
			<img src="<?php echo $this->getSkinUrl( 'images/anattadesign/awesomecheckout/opc-ajax-loader.gif' ) ?>" alt="<?php echo $this->__( 'Loading next step...' ) ?>" title="<?php echo $this->__( 'Loading next step...' ) ?>" class="v-middle" /> <?php echo $this->__( 'Loading next step...' ) ?>
		</span>
	</footer>
</form>